name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.1'
        bundler-cache: true

    - name: Generate coverage for smoke test projects
      run: |
        # Generate coverage for calculator_cli
        cd smoke/calculator_cli
        bundle exec rspec --require spec_helper 2>/dev/null || true
        cd ../..
        
        # Generate coverage for sample_app  
        cd smoke/sample_app
        bundle exec rspec --require spec_helper 2>/dev/null || true
        cd ../..

    - name: Run RSpec
      run: bundle exec rspec
